version: '3.8'

services:
  client:
    build:
      context: ./app/client
      dockerfile: Dockerfile
    container_name: client
    restart: always
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    networks:
      - my_network

  nginx:
    image: nginx:1.26
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
    ports:
      - "80:80"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
